"""change

Revision ID: 47cf1524cb0d
Revises: 
Create Date: 2024-01-30 09:50:21.435731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '47cf1524cb0d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Employees',
    sa.Column('EmpID', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=20), nullable=True),
    sa.Column('LastName', sa.String(length=20), nullable=True),
    sa.Column('StartDate', sa.Date(), nullable=True),
    sa.Column('ExitDate', sa.Date(), nullable=True),
    sa.Column('Title', sa.String(length=30), nullable=True),
    sa.Column('Supervisor', sa.String(length=30), nullable=True),
    sa.Column('ADEmail', sa.String(length=100), nullable=True),
    sa.Column('EmployeeStatus', sa.String(length=20), nullable=True),
    sa.Column('EmployeeType', sa.String(length=20), nullable=True),
    sa.Column('EmployeeClassificationType', sa.String(length=20), nullable=True),
    sa.Column('TerminationType', sa.String(length=20), nullable=True),
    sa.Column('TerminationDescription', sa.String(length=150), nullable=True),
    sa.Column('DepartmentType', sa.String(length=20), nullable=True),
    sa.Column('Division', sa.String(length=20), nullable=True),
    sa.Column('DOB', sa.Date(), nullable=True),
    sa.Column('State', sa.String(length=10), nullable=True),
    sa.Column('JobFunctionDescription', sa.String(length=20), nullable=True),
    sa.Column('GenderCode', sa.String(length=10), nullable=True),
    sa.Column('LocationCode', sa.Integer(), nullable=True),
    sa.Column('RaceDesc', sa.String(length=10), nullable=True),
    sa.Column('MaritalDesc', sa.String(length=20), nullable=True),
    sa.Column('PerformanceScore', sa.String(length=20), nullable=True),
    sa.Column('CurrentEmployeeRating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('EmpID'),
    sa.UniqueConstraint('ADEmail')
    )
    op.drop_index('ADEmail', table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('EmpID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('FirstName', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('LastName', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('StartDate', sa.DATE(), nullable=True),
    sa.Column('ExitDate', sa.DATE(), nullable=True),
    sa.Column('Title', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('Supervisor', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('ADEmail', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('EmployeeStatus', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('EmployeeType', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('EmployeeClassificationType', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('TerminationType', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('TerminationDescription', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('DepartmentType', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('Division', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('DOB', sa.DATE(), nullable=True),
    sa.Column('State', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('JobFunctionDescription', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('GenderCode', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('LocationCode', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('RaceDesc', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('MaritalDesc', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('PerformanceScore', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('CurrentEmployeeRating', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('EmpID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ADEmail', 'employees', ['ADEmail'], unique=True)
    op.drop_table('Employees')
    # ### end Alembic commands ###
